// import { ResumenResponse } from "../types/types";

// export const getMockResumen = (): ResumenResponse => ({
//   icoPromedio: 94,
//   topRoles: [
//     {
//       id: 1,
//       cargo: "Director General",
//       prioridades: 5,
//       objetivos: 8,
//       proyectos: 3,
//       ico: 92,
//       icp: 88,
//     },
//     {
//       id: 2,
//       cargo: "Director de Tecnología",
//       prioridades: 4,
//       objetivos: 7,
//       proyectos: 4,
//       ico: 88,
//       icp: 85,
//     },
//     {
//       id: 3,
//       cargo: "Director de Operaciones",
//       prioridades: 6,
//       objetivos: 9,
//       proyectos: 5,
//       ico: 79,
//       icp: 82,
//     },
//     {
//       id: 4,
//       cargo: "Director de Recursos Humanos",
//       prioridades: 3,
//       objetivos: 6,
//       proyectos: 2,
//       ico: 85,
//       icp: 80,
//     },
//     {
//       id: 5,
//       cargo: "Jefe de Desarrollo",
//       prioridades: 8,
//       objetivos: 12,
//       proyectos: 6,
//       ico: 76,
//       icp: 78,
//     },
//   ],
//   allRoles: [
//     {
//       id: 1,
//       cargo: "Director General",
//       prioridades: 5,
//       objetivos: 8,
//       proyectos: 3,
//       ico: 92,
//       icp: 88,
//     },
//     {
//       id: 2,
//       cargo: "Director de Tecnología",
//       prioridades: 4,
//       objetivos: 7,
//       proyectos: 4,
//       ico: 88,
//       icp: 85,
//     },
//     {
//       id: 3,
//       cargo: "Director de Operaciones",
//       prioridades: 6,
//       objetivos: 9,
//       proyectos: 5,
//       ico: 79,
//       icp: 82,
//     },
//     {
//       id: 4,
//       cargo: "Director de Recursos Humanos",
//       prioridades: 3,
//       objetivos: 6,
//       proyectos: 2,
//       ico: 85,
//       icp: 80,
//     },
//     {
//       id: 5,
//       cargo: "Jefe de Desarrollo",
//       prioridades: 8,
//       objetivos: 12,
//       proyectos: 6,
//       ico: 76,
//       icp: 78,
//     },
//     {
//       id: 6,
//       cargo: "Jefe de Infraestructura",
//       prioridades: 7,
//       objetivos: 10,
//       proyectos: 4,
//       ico: 82,
//       icp: 75,
//     },
//     {
//       id: 7,
//       cargo: "Jefe de Calidad",
//       prioridades: 5,
//       objetivos: 8,
//       proyectos: 3,
//       ico: 90,
//       icp: 92,
//     },
//     {
//       id: 8,
//       cargo: "Desarrollador Senior",
//       prioridades: 3,
//       objetivos: 5,
//       proyectos: 2,
//       ico: 95,
//       icp: 90,
//     },
//     {
//       id: 9,
//       cargo: "Desarrollador Junior",
//       prioridades: 2,
//       objetivos: 4,
//       proyectos: 1,
//       ico: 70,
//       icp: 65,
//     },
//     {
//       id: 10,
//       cargo: "Especialista en Talento",
//       prioridades: 4,
//       objetivos: 6,
//       proyectos: 2,
//       ico: 88,
//       icp: 90,
//     },
//     {
//       id: 11,
//       cargo: "Coordinador de Nómina",
//       prioridades: 3,
//       objetivos: 5,
//       proyectos: 2,
//       ico: 82,
//       icp: 85,
//     },
//   ],
// });
