services:
  frontend-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-qa
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${FRONT_PORT:-3000}
      # Público (browser)
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      # Interno (SSR/ISR) por la red Docker compartida
      API_BASE_URL_INTERNAL: http://backend-qa:4000/api/v1
    ports:
      - "${HOST_DOCKER_FRONT_PORT:-3000}:${FRONT_PORT:-3000}"
    networks:
      - soe-qa-network

networks:
  soe-qa-network:
    external: true
    name: arco-soe-api_soe-qa-network
