export const PERMISSIONS = {
  PERFORMANCE: {
    MENU: "performance.menu",
    SHOW_FILTER_STRATEGIC_PLAN: "performance.showFilterStrategicPlan",
    SHOW_FILTER_POSITION: "performance.showFilterPosition",
    SHOW_FILTER_MONTH: "performance.showFilterMonth",
    SHOW_FILTER_YEAR: "performance.showFilterYear",
    SHOW_ICO_CHART: "performance.showIcoChart",
    SHOW_ICP_CHART: "performance.showIcpChart",
    SHOW_PERFORMANCE_CHART: "performance.showPerformanceChart",
    SHOW_ASSIGNMENTS_CHART: "performance.showAssignmentsChart",
    SHOW_ANNUAL_PERFORMANCE_TREND_CHART:
      "performance.showAnnualPerformanceTrendChart",
    SHOW_PERFORMANCE_MAP_CHART: "performance.showPerformanceMapChart",
    SHOW_POSITION_SUMMARY_TABLE: "performance.showPositionSummaryTable",
  },
  STRATEGIC_PLANS: {
    MENU: "strategicPlans.menu",
    MENU_CONFIG: "strategicPlans.menuConfig",
    SHOW_FILTER_STRATEGIC_PLAN: "strategicPlans.showFilterStrategicPlan",
    SHOW_DEFINITION_TAB: "strategicPlans.showDefinitionTab",
    SHOW_STRATEGIC_MAP_TAB: "strategicPlans.showStrategicMapTab",
    DOWNLOAD_REPORT_PDF: "strategicPlans.downloadReportPdf",
    READ: "strategicPlans.read",
    CREATE: "strategicPlans.create",
    UPDATE: "strategicPlans.update",
    DELETE: "strategicPlans.delete",
    REORDER: "strategicPlans.reorder",
    ADD_NOTE: "strategicPlans.addNote",
    UPLOAD_DOCUMENT: "strategicPlans.uploadDocument",
    AUDIT: "strategicPlans.audit",
  },
  STRATEGIC_SUCCESS_FACTORS: {
    READ: "strategicSuccessFactor.read",
    CREATE: "strategicSuccessFactor.create",
    UPDATE: "strategicSuccessFactor.update",
    DELETE: "strategicSuccessFactor.delete",
    REORDER: "strategicSuccessFactor.reorder",
    AUDIT: "strategicSuccessFactor.audit",
  },
  STRATEGIC_VALUES: {
    READ: "strategicValues.read",
    CREATE: "strategicValues.create",
    UPDATE: "strategicValues.update",
    DELETE: "strategicValues.delete",
    REORDER: "strategicValues.reorder",
    AUDIT: "strategicValues.audit",
  },
  OBJECTIVES: {
    MENU: "objectives.menu",
    SHOW_FILTER_STRATEGIC_PLAN: "objectives.showFilterStrategicPlan",
    SHOW_FILTER_POSITION: "objectives.showFilterPosition",
    SHOW_FILTER_YEAR: "objectives.showFilterYear",
    SHOW_ICO_BOARD_TAB: "objectives.showIcoBoardTab",
    SHOW_COMPLIANCE_TAB: "objectives.showComplianceTab",
    READ: "objectives.read",
    CREATE: "objectives.create",
    UPDATE: "objectives.update",
    DELETE: "objectives.delete",
    REORDER: "objectives.reorder",
    ADD_NOTE: "objectives.addNote",
    UPLOAD_DOCUMENT: "objectives.uploadDocument",
    AUDIT: "objectives.audit",
  },
  OBJECTIVE_GOALS: {
    UPDATE: "objectiveGoals.update",
    UPDATE_COMPLIANCE: "objectiveGoals.updateCompliance",
    UPDATE_TARGET_VALUE: "objectiveGoals.updateTargetValue",
  },
  STRATEGIC_PROJECTS: {
    MENU: "strategicProjects.menu",
    SHOW_FILTER_STRATEGIC_PLAN: "strategicProjects.showFilterStrategicPlan",
    SHOW_FILTER_POSITION: "strategicProjects.showFilterPosition",
    READ: "strategicProjects.read",
    CREATE: "strategicProjects.create",
    UPDATE: "strategicProjects.update",
    DELETE: "strategicProjects.delete",
    REORDER: "strategicProjects.reorder",
    DOWNLOAD_REPORT_PDF: "strategicProjects.downloadReportPdf",
    AUDIT: "strategicProjects.audit",
  },
  PROJECT_FACTORS: {
    READ: "projectFactors.read",
    CREATE: "projectFactors.create",
    UPDATE: "projectFactors.update",
    DELETE: "projectFactors.delete",
    REORDER: "projectFactors.reorder",
    AUDIT: "projectFactors.audit",
  },
  PROJECT_TASKS: {
    READ: "projectTasks.read",
    CREATE: "projectTasks.create",
    UPDATE: "projectTasks.update",
    DELETE: "projectTasks.delete",
    REORDER: "projectTasks.reorder",
    AUDIT: "projectTasks.audit",
  },
  POSITIONS: {
    MENU: "positions.menu",
    MENU_CONFIG: "positions.menuConfig",
    SHOW_FILTER_STRATEGIC_PLAN: "positions.showFilterStrategicPlan",
    SHOW_FILTER_POSITION: "positions.showFilterPosition",
    SHOW_FILTER_MONTH: "positions.showFilterMonth",
    SHOW_FILTER_YEAR: "positions.showFilterYear",
    SHOW_DEFINITION_TAB: "positions.showDefinitionTab",
    SHOW_ORG_CHART_TAB: "positions.showOrgChartTab",
    DOWNLOAD_REPORT_PDF: "positions.downloadReportPdf",
    READ: "positions.read",
    CREATE: "positions.create",
    UPDATE: "positions.update",
    DELETE: "positions.delete",
    REORDER: "positions.reorder",
    ADD_NOTE: "positions.addNote",
    UPLOAD_DOCUMENT: "positions.uploadDocument",
    SET_BUSINESS_UNITS: "positions.setBusinessUnits",
    SET_USERS: "positions.setUsers",
    SET_PARENT_POSITION: "positions.setParentPosition",
    AUDIT: "positions.audit",
  },
  LEVERS: {
    READ: "levers.read",
    CREATE: "levers.create",
    UPDATE: "levers.update",
    DELETE: "levers.delete",
    REORDER: "levers.reorder",
    AUDIT: "levers.audit",
  },
  PRIORITIES: {
    MENU: "priorities.menu",
    SHOW_FILTER_STRATEGIC_PLAN: "priorities.showFilterStrategicPlan",
    SHOW_FILTER_POSITION: "priorities.showFilterPosition",
    SHOW_FILTER_MONTH: "priorities.showFilterMonth",
    SHOW_FILTER_YEAR: "priorities.showFilterYear",
    SHOW_STATUS_CHART: "priorities.showStatusChart",
    SHOW_ANNUAL_ICP_TREND_CHART: "priorities.showAnnualIcpTrendChart",
    DOWNLOAD_REPORT_PDF: "priorities.downloadReportPdf",
    READ: "priorities.read",
    CREATE: "priorities.create",
    UPDATE: "priorities.update",
    DELETE: "priorities.delete",
    REORDER: "priorities.reorder",
    ADD_NOTE: "priorities.addNote",
    UPLOAD_DOCUMENT: "priorities.uploadDocument",
    UPDATE_FINISHED_AT: "priorities.updateFinishedAt",
    UPDATE_DATE_RANGE: "priorities.updateDateRange",
    AUDIT: "priorities.audit",
  },
  COMPANIES: {
    MENU_CONFIG: "companies.menuConfig",
    READ: "companies.read",
    CREATE: "companies.create",
    UPDATE: "companies.update",
    DELETE: "companies.delete",
    REORDER: "companies.reorder",
    ADD_NOTE: "companies.addNote",
    UPLOAD_DOCUMENT: "companies.uploadDocument",
    AUDIT: "companies.audit",
  },
  BUSINESS_UNITS: {
    MENU_CONFIG: "businessUnits.menuConfig",
    READ: "businessUnits.read",
    CREATE: "businessUnits.create",
    UPDATE: "businessUnits.update",
    DELETE: "businessUnits.delete",
    REORDER: "businessUnits.reorder",
    ADD_NOTE: "businessUnits.addNote",
    UPLOAD_DOCUMENT: "businessUnits.uploadDocument",
    AUDIT: "businessUnits.audit",
  },
  USERS: {
    MENU_CONFIG: "users.menuConfig",
    READ: "users.read",
    CREATE: "users.create",
    UPDATE: "users.update",
    DELETE: "users.delete",
    REORDER: "users.reorder",
    ADD_NOTE: "users.addNote",
    UPLOAD_DOCUMENT: "users.uploadDocument",
    SET_PERMISSIONS: "users.setPermissions",
    SET_ROLES: "users.setRoles",
    SET_BUSINESS_UNITS: "users.setBusinessUnits",
    AUDIT: "users.audit",
  },
  MODULES: {
    MENU_CONFIG: "modules.menuConfig",
    READ: "modules.read",
    CREATE: "modules.create",
    UPDATE: "modules.update",
    DELETE: "modules.delete",
    REORDER: "modules.reorder",
    SET_PERMISSIONS: "modules.setPermissions",
    AUDIT: "modules.audit",
  },
  ROLES: {
    MENU_CONFIG: "roles.menuConfig",
    READ: "roles.read",
    CREATE: "roles.create",
    UPDATE: "roles.update",
    DELETE: "roles.delete",
    REORDER: "roles.reorder",
    SET_PERMISSIONS: "roles.setPermissions",
    AUDIT: "roles.audit",
  },
  NOTIFICATIONS: {
    MENU: "notifications.menu",
    MENU_CONFIG: "notifications.menuConfig",
    READ: "notifications.read",
    CREATE: "notifications.create",
    UPDATE: "notifications.update",
    DELETE: "notifications.delete",
    AUDIT: "notifications.audit",
  },
  PERMISSIONS: {
    MENU: "permissions.menu",
    MENU_CONFIG: "permissions.menuConfig",
    READ: "permissions.read",
    CREATE: "permissions.create",
    UPDATE: "permissions.update",
    DELETE: "permissions.delete",
    AUDIT: "permissions.audit",
  },
  SYSTEM_SETTINGS: {
    MENU_CONFIG: "systemSettings.menuConfig",
    READ: "systemSettings.read",
    CREATE: "systemSettings.create",
    UPDATE: "systemSettings.update",
    DELETE: "systemSettings.delete",
    AUDIT: "systemSettings.audit",
  },
};
